package main

import (
	"archive/tar"
	"bytes"
	"encoding/json"
	"io"
	"os/exec"
	"slices"
	"strings"
	"testing"
)

func TestInlineDockerfileGoldenOutput(t *testing.T) {
	const build = `{
      "from": "node:24-slim",
      "packages": ["git", "curl"],
      "workdir": "/app",
      "run": [
        "corepack enable && corepack prepare pnpm@11.16.0 --activate",
        "pnpm install --frozen-lockfile",
        "pnpm --filter web build"
      ],
      "env": {"NODE_ENV": "production", "PORT": "3000"},
      "expose": 3000,
      "start": "pnpm --filter web start -H 0.0.0.0"
    }`

	inline, isInline, err := ParseInlineBuild(json.RawMessage(build))
	if err != nil {
		t.Fatalf("ParseInlineBuild: %v", err)
	}
	if !isInline {
		t.Fatal("a block with a from is the inline form")
	}

	rendered, err := inline.RenderDockerfile("web")
	if err != nil {
		t.Fatalf("RenderDockerfile: %v", err)
	}

	const want = `# generated by deploy from the build block in .deploy.json.
# edits here are lost on the next deploy.
#
# this is a single stage build, which has two consequences worth knowing.
# COPY comes before the run steps, so any source change re-runs all of
# them, and there is no --platform=$BUILDPLATFORM split, so a cross
# architecture build emulates the whole way through. both are fine for a
# small service and neither is fine for a large one. the fix for both is
# to write a real Dockerfile and point build.dockerfile at it.

FROM node:24-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends git curl \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN corepack enable && corepack prepare pnpm@11.16.0 --activate
RUN pnpm install --frozen-lockfile
RUN pnpm --filter web build

ENV NODE_ENV="production"
ENV PORT="3000"

EXPOSE 3000

CMD ["sh","-c","pnpm --filter web start -H 0.0.0.0"]
`

	if rendered != want {
		t.Errorf("rendered Dockerfile does not match.\n--- got ---\n%s\n--- want ---\n%s", rendered, want)
	}
}

func TestPackageManagerIsDeclaredRatherThanGuessed(t *testing.T) {
	cases := []struct {
		name    string
		build   string
		want    string
		refused bool
	}{
		{
			name:  "apt is the default",
			build: `{"from": "debian:13", "packages": ["git"]}`,
			want:  "apt-get install -y --no-install-recommends git",
		},
		{
			name:  "apk when asked for",
			build: `{"from": "alpine:3", "packageManager": "apk", "packages": ["git"]}`,
			want:  "apk add --no-cache git",
		},
		{
			// an alpine base with no packageManager still uses apt, because
			// guessing from the image name is how this becomes framework detection
			name:  "an alpine base is not sniffed",
			build: `{"from": "alpine:3", "packages": ["git"]}`,
			want:  "apt-get install",
		},
		{
			name:    "an unknown package manager is refused",
			build:   `{"from": "alpine:3", "packageManager": "yum", "packages": ["git"]}`,
			refused: true,
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			inline, _, err := ParseInlineBuild(json.RawMessage(testCase.build))
			if err != nil {
				t.Fatalf("ParseInlineBuild: %v", err)
			}

			rendered, err := inline.RenderDockerfile("web")

			if testCase.refused {
				if err == nil {
					t.Fatal("an unknown package manager should be refused rather than guessed at")
				}
				if !strings.Contains(err.Error(), "apk") || !strings.Contains(err.Error(), "apt") {
					t.Errorf("the refusal should say what is known, got: %v", err)
				}
				return
			}
			if err != nil {
				t.Fatalf("RenderDockerfile: %v", err)
			}
			if !strings.Contains(rendered, testCase.want) {
				t.Errorf("expected %q in:\n%s", testCase.want, rendered)
			}
		})
	}
}

func TestTheInlineFormIsOnlyChosenWhenFromIsPresent(t *testing.T) {
	cases := []struct {
		build       string
		wantInline  bool
		wantRefusal bool
	}{
		{build: `{"from": "node:24"}`, wantInline: true},
		{build: `{"dockerfile": "Dockerfile"}`, wantInline: false},
		{build: `"Dockerfile"`, wantInline: false},
		{build: `{}`, wantInline: false},
		// both at once is two different ways to build, and picking one silently
		// would mean ignoring something somebody wrote on purpose
		{build: `{"from": "node:24", "dockerfile": "Dockerfile"}`, wantRefusal: true},
	}

	for _, testCase := range cases {
		t.Run(testCase.build, func(t *testing.T) {
			_, isInline, err := ParseInlineBuild(json.RawMessage(testCase.build))

			if testCase.wantRefusal {
				if err == nil {
					t.Fatal("declaring both forms should be refused")
				}
				return
			}
			if err != nil {
				t.Fatalf("ParseInlineBuild: %v", err)
			}
			if isInline != testCase.wantInline {
				t.Errorf("isInline = %v, want %v", isInline, testCase.wantInline)
			}
		})
	}
}

func TestDeclaringBothBuildFormsIsRejectedAtValidation(t *testing.T) {
	const contents = `{
      "version": 1, "id": "a3f19c02", "name": "x",
      "services": {"web": {"build": {"from": "node:24", "dockerfile": "Dockerfile"}}}
    }`

	err := loadAndResolve(t, contents, defaultEnvironmentName).Validate()
	if err == nil {
		t.Fatal("a service declaring both build forms should not reach a deploy")
	}
	if !strings.Contains(err.Error(), "pick one") {
		t.Errorf("got: %v", err)
	}
}

func TestAMinimalInlineBuildRendersWithoutTheOptionalParts(t *testing.T) {
	inline, _, err := ParseInlineBuild(json.RawMessage(`{"from": "busybox:latest"}`))
	if err != nil {
		t.Fatalf("ParseInlineBuild: %v", err)
	}

	rendered, err := inline.RenderDockerfile("app")
	if err != nil {
		t.Fatalf("RenderDockerfile: %v", err)
	}

	if !strings.Contains(rendered, "FROM busybox:latest") {
		t.Error("the base image is the one thing an inline build must have")
	}
	for _, absent := range []string{"RUN apt-get", "WORKDIR", "ENV ", "EXPOSE", "CMD"} {
		if strings.Contains(rendered, absent) {
			t.Errorf("nothing asked for %s, so it should not be rendered:\n%s", absent, rendered)
		}
	}
	if !strings.Contains(rendered, "COPY . .") {
		t.Error("the source still has to get into the image")
	}
}

func TestContextInjectionAddsTheGeneratedFileAndKeepsTheRest(t *testing.T) {
	var original bytes.Buffer
	writer := tar.NewWriter(&original)

	for name, contents := range map[string]string{
		"main.go":    "package main",
		"go.mod":     "module x",
		"Dockerfile": "FROM scratch",
	} {
		if err := writer.WriteHeader(&tar.Header{
			Name: name, Mode: 0o644, Size: int64(len(contents)),
		}); err != nil {
			t.Fatalf("writing header: %v", err)
		}
		if _, err := writer.Write([]byte(contents)); err != nil {
			t.Fatalf("writing entry: %v", err)
		}
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("closing: %v", err)
	}

	var injected bytes.Buffer
	generated := generatedDockerfileName("web")
	err := addToTar(&original, &injected, map[string][]byte{
		generated:    []byte("FROM node:24"),
		"Dockerfile": []byte("ours wins"),
	})
	if err != nil {
		t.Fatalf("addToTar: %v", err)
	}

	found := map[string]string{}
	var order []string

	reader := tar.NewReader(&injected)
	for {
		header, err := reader.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatalf("reading back: %v", err)
		}
		contents, err := io.ReadAll(reader)
		if err != nil {
			t.Fatalf("reading entry: %v", err)
		}
		found[header.Name] = string(contents)
		order = append(order, header.Name)
	}

	if found["main.go"] != "package main" {
		t.Errorf("an existing file was lost or changed, got %q", found["main.go"])
	}
	if found[generated] != "FROM node:24" {
		t.Errorf("the generated file did not arrive, got %q", found[generated])
	}
	// a file of the same name in the commit must not shadow what deploy generated
	if found["Dockerfile"] != "ours wins" {
		t.Errorf("an injected file should replace one of the same name, got %q", found["Dockerfile"])
	}

	// counted as a list rather than a map, because two entries of the same name
	// collapse in a map and would hide the replacement never happening
	if len(order) != 4 {
		t.Errorf("expected four entries with no duplicates, got %v", order)
	}
	if slices.Contains(order[:len(order)-2], "Dockerfile") && slices.Contains(order[len(order)-2:], "Dockerfile") {
		t.Errorf("the original Dockerfile was left in alongside ours, got %v", order)
	}
}

// The tar end-of-archive marker comes before git archive's block padding, so a
// reader that stops at the marker leaves bytes behind and git blocks forever
// writing them. That deadlock hangs a deploy rather than failing it, which is
// exactly the failure mode worth a fast, deterministic test.
func TestContextInjectionDrainsEverythingItWasGiven(t *testing.T) {
	var source bytes.Buffer

	writer := tar.NewWriter(&source)
	if err := writer.WriteHeader(&tar.Header{Name: "a.txt", Mode: 0o644, Size: 1}); err != nil {
		t.Fatalf("writing header: %v", err)
	}
	if _, err := writer.Write([]byte("x")); err != nil {
		t.Fatalf("writing entry: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("closing: %v", err)
	}

	// what git archive appends past the marker, and what a stopped reader leaves
	trailing := make([]byte, 4096)
	source.Write(trailing)

	if err := addToTar(&source, io.Discard, map[string][]byte{"added": []byte("x")}); err != nil {
		t.Fatalf("addToTar: %v", err)
	}

	if remaining := source.Len(); remaining != 0 {
		t.Errorf(
			"%d bytes left unread, which over a pipe is git blocked forever and a deploy that hangs",
			remaining,
		)
	}
}

func TestAServiceBuiltFromAnInlineBlockActuallyRuns(t *testing.T) {
	dockerAvailable(t)

	repository := newRepository(t)
	writeFile(t, repository, configFileName, `{
      "version": 1,
      "id": "dd000010",
      "name": "inlinebuilt",
      "services": {
        "app": {
          "build": {
            "from": "busybox:latest",
            "workdir": "/app",
            "env": {"GREETING": "from an inline build"},
            "start": "cat /app/marker.txt; echo $GREETING; sleep 300"
          },
          "stateful": false,
          "healthcheck": {"command": ["CMD", "true"], "interval": "1s", "retries": 5}
        }
      }
    }`)
	commit := commitFile(t, repository, "marker.txt", "the committed tree")

	destination := t.TempDir()
	t.Cleanup(func() {
		exec.Command("docker", "compose", "--project-name", ProjectName("dd000010", commit), "down").Run()
		exec.Command("docker", "image", "rm", "-f", ImageTag("dd000010", "app", commit)).Run()
		exec.Command("docker", "network", "rm", NetworkName("dd000010")).Run()
	})

	if _, err := RunDeploy(DeployOptions{
		Context: repository, Destination: destination, Environment: defaultEnvironmentName,
	}); err != nil {
		t.Fatalf("deploying a service with no Dockerfile of its own: %v", err)
	}

	container, err := exec.Command(
		"docker", "ps", "--filter", "name="+ProjectName("dd000010", commit), "--format", "{{.Names}}",
	).Output()
	if err != nil || strings.TrimSpace(string(container)) == "" {
		t.Fatalf("the inline built service should be running: %v", err)
	}

	// the source reached the image, and so did the env the shorthand declared
	inside, err := exec.Command(
		"docker", "exec", strings.TrimSpace(string(container)), "sh", "-c", "cat /app/marker.txt; echo $GREETING",
	).Output()
	if err != nil {
		t.Fatalf("reading from the container: %v", err)
	}
	for _, want := range []string{"the committed tree", "from an inline build"} {
		if !strings.Contains(string(inside), want) {
			t.Errorf("expected %q in the container, got %q", want, inside)
		}
	}

	// and nothing was written into the checkout
	if entries, _ := exec.Command("git", "-C", repository, "status", "--porcelain").Output(); len(entries) > 0 {
		t.Errorf("the generated Dockerfile leaked into the repository: %s", entries)
	}
}
