package main

import (
	"encoding/json"
	"fmt"
	"maps"
	"slices"
	"strconv"
	"strings"
)

// generatedDockerfileName is what an inline build is rendered to. It carries the
// service name so two inline services in one repo cannot collide, and it is
// injected into the build context rather than written into anyone's checkout.
func generatedDockerfileName(serviceName string) string {
	return "Dockerfile.deploy-" + serviceName
}

// InlineBuild is the shorthand for a service that needs four lines and a start
// command. It renders a Dockerfile rather than being a second build system, and
// anything it cannot say is a reason to write a real Dockerfile instead.
type InlineBuild struct {
	From           string            `json:"from"`
	PackageManager string            `json:"packageManager,omitempty"`
	Packages       []string          `json:"packages,omitempty"`
	Workdir        string            `json:"workdir,omitempty"`
	Run            []string          `json:"run,omitempty"`
	Env            map[string]string `json:"env,omitempty"`
	Expose         int               `json:"expose,omitempty"`
	Start          string            `json:"start,omitempty"`
}

// packageInstallers are spelled out rather than guessed from the base image,
// because sniffing is how this turns into the framework detection we are here to
// avoid.
var packageInstallers = map[string]func([]string) string{
	"apt": func(packages []string) string {
		return "apt-get update \\\n && apt-get install -y --no-install-recommends " +
			strings.Join(packages, " ") +
			" \\\n && rm -rf /var/lib/apt/lists/*"
	},
	"apk": func(packages []string) string {
		return "apk add --no-cache " + strings.Join(packages, " ")
	},
}

// ParseInlineBuild reports whether a build block is the inline form at all. A
// bare string or an object naming a dockerfile is the other form.
func ParseInlineBuild(raw json.RawMessage) (InlineBuild, bool, error) {
	var probe struct {
		Dockerfile string `json:"dockerfile"`
		From       string `json:"from"`
	}
	if err := json.Unmarshal(raw, &probe); err != nil {
		return InlineBuild{}, false, nil
	}
	if probe.From == "" {
		return InlineBuild{}, false, nil
	}
	if probe.Dockerfile != "" {
		return InlineBuild{}, false, fmt.Errorf(
			"a build block sets both dockerfile and from, and those are two different ways to build. pick one",
		)
	}

	var inline InlineBuild
	if err := json.Unmarshal(raw, &inline); err != nil {
		return InlineBuild{}, false, fmt.Errorf("unreadable inline build: %w", err)
	}

	return inline, true, nil
}

// RenderDockerfile turns the shorthand into a real Dockerfile. It is single
// stage, and says so in its own header, because both of its ceilings follow from
// that and whoever hits one needs to know where to go next.
func (inline InlineBuild) RenderDockerfile(serviceName string) (string, error) {
	if inline.From == "" {
		return "", fmt.Errorf("service %q has an inline build with no from", serviceName)
	}

	manager := inline.PackageManager
	if manager == "" {
		manager = "apt"
	}
	install, known := packageInstallers[manager]
	if !known {
		return "", fmt.Errorf(
			"service %q asks for packageManager %q, and deploy knows %s",
			serviceName, manager, strings.Join(slices.Sorted(maps.Keys(packageInstallers)), " and "),
		)
	}

	var rendered strings.Builder

	rendered.WriteString("# generated by deploy from the build block in " + configFileName + ".\n")
	rendered.WriteString("# edits here are lost on the next deploy.\n")
	rendered.WriteString("#\n")
	rendered.WriteString("# this is a single stage build, which has two consequences worth knowing.\n")
	rendered.WriteString("# COPY comes before the run steps, so any source change re-runs all of\n")
	rendered.WriteString("# them, and there is no --platform=$BUILDPLATFORM split, so a cross\n")
	rendered.WriteString("# architecture build emulates the whole way through. both are fine for a\n")
	rendered.WriteString("# small service and neither is fine for a large one. the fix for both is\n")
	rendered.WriteString("# to write a real Dockerfile and point build.dockerfile at it.\n")
	rendered.WriteString("\nFROM " + inline.From + "\n")

	if len(inline.Packages) > 0 {
		rendered.WriteString("\nRUN " + install(inline.Packages) + "\n")
	}
	if inline.Workdir != "" {
		rendered.WriteString("\nWORKDIR " + inline.Workdir + "\n")
	}

	rendered.WriteString("\nCOPY . .\n")

	if len(inline.Run) > 0 {
		rendered.WriteString("\n")
		for _, step := range inline.Run {
			rendered.WriteString("RUN " + step + "\n")
		}
	}

	if len(inline.Env) > 0 {
		rendered.WriteString("\n")
		for _, name := range slices.Sorted(maps.Keys(inline.Env)) {
			// quoted always, because an unquoted value with a space in it is not
			// an ENV with a space, it is a syntax error, and "a b" is an entirely
			// ordinary thing to want
			rendered.WriteString("ENV " + name + "=" + strconv.Quote(inline.Env[name]) + "\n")
		}
	}

	if inline.Expose > 0 {
		rendered.WriteString(fmt.Sprintf("\nEXPOSE %d\n", inline.Expose))
	}

	if inline.Start != "" {
		// through a shell, so a start command can use pipes and variables the way
		// it would if it were typed
		start, err := json.Marshal([]string{"sh", "-c", inline.Start})
		if err != nil {
			return "", err
		}
		rendered.WriteString("\nCMD " + string(start) + "\n")
	}

	return rendered.String(), nil
}
